# PyInstaller hook for reportlab
# This ensures all reportlab dependencies are properly included

from PyInstaller.utils.hooks import collect_submodules, collect_data_files

# Collect all reportlab submodules
hiddenimports = collect_submodules('reportlab')

# Add specific modules that reportlab needs
hiddenimports += [
    'email',
    'email.utils',
    'email.header',
    'email.message',
    'email.parser',
    'email.generator',
    'email.encoders',
    'email.base64mime',
    'email.quoprimime',
    'email.mime',
    'email.mime.base',
    'email.mime.multipart',
    'email.mime.text',
    'smtplib',
    'imaplib',
    'calendar',
    'gzip',
    'base64',
    'uu',
    'binascii',
    'hashlib',
    'ssl',
    'urllib.request',
    'json',
    'csv',
    'xml.etree.ElementTree',
    'secrets',  # For numpy compatibility
    'http',
    'http.client',
    'http.server',
    'http.cookies',
    'http.cookiejar',
    'urllib',
    'urllib.parse',
    'urllib.error',
    'socket',
    'select',
    'threading',
    'multiprocessing',
    'subprocess',
    'tempfile',
    'shutil',
    'glob',
    'fnmatch',
    'linecache',
    'tokenize',
    'keyword',
    'ast',
    'inspect',
    'dis',
    'opcode',
    'copyreg',
    'copy',
    'pprint',
    'reprlib',
    'enum',
    'numbers',
    'math',
    'cmath',
    'decimal',
    'fractions',
    'random',
    'statistics',
    'collections',
    'collections.abc',
    'functools',
    'operator',
    'itertools',
    'contextlib',
    'warnings',
    'weakref',
    'gc',
    'sys',
    '_sys',
    'builtins',
    'types',
    'platform',
    'errno',
    'ctypes',
    'msvcrt',  # Windows-specific
    'nt',      # Windows-specific
    'posix',   # Unix-specific
]

# Collect any data files reportlab might need
datas = collect_data_files('reportlab')